include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
  #- template: 'Security/SAST.gitlab-ci.yml'  


variables:
  DEV_USER: student
  DEV_HOST: std-019-32.praktikum-services.tech
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
   - build
   #- test 
   - release
   - deploy


build:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - docker build --build-arg VERSION=$VERSION --tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA

#отключаем ненужные тесты, которые относятся к backend
#spotbugs-sast:
#  rules:
#   - when: never

#sonarqube-sast:
#  stage: test
#  image:
#    name: sonarsource/sonar-scanner-cli:latest
#    entrypoint: [""]
#  script:
#    - cd frontend
#    - > 
#      sonar-scanner
#      -Dsonar.sources=. 
#      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT}
#      -Dsonar.host.url=${SONARQUBE_URL}
#      -Dsonar.login=${SONAR_LOGIN_FRONT}
#      -Dsonar.projectName=19_ALEXANDERVOZNYY_FRONT
#      -Dsonar.qualitygate.wait=true


upload-latest:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA
    # если образ прошел проверки в CI (сканирование, тесты и т.д), то тегаем latest
    - docker tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/sausage-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:latest
         

deploy-frontend:
  stage: deploy
  image: alpine:3.15.0
  #when: manual 
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp ./docker-compose.yml ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/docker-compose.yml
    - scp ./frontend/nginx.tmpl ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/frontend/nginx.tmpl
    - ssh ${DEV_USER}@${DEV_HOST}
       "export "CI_REGISTRY_USER=${CI_REGISTRY_USER}";
       export "CI_JOB_TOKEN=${CI_JOB_TOKEN}";
       export "CI_REGISTRY=${CI_REGISTRY}";
       export "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}";
       export "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}";
       export "SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}";
       export "VERSION=latest";
      /bin/bash -s " < ./frontend/deploy.sh 
  #needs:
  #  - job: upload-latest 
       

