apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi1pY3A3cGVxNndta29jMmxoLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE5LTAzMg==
  SPRING_DATASOURCE_USERNAME: c3RkLTAxOS0wMzI=
  SPRING_DATASOURCE_PASSWORD: VGVzdHVzcjEyMzQ=
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL3N0ZC0wMTktMDMyOlRlc3R1c3IxMjM0QHJjMWEtcnJxa3RtZzhqamE3aDQ4OC5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC0wMTktMDMy
