---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLkNBRVNJS0tJYjJYN21SVjNfb0d3RG12R1ZRd1Q0WHk5cE5YWnBkYnRnNXZKWkY1RUdoNEtIR2gyY3k1clRWWnJWRk15ZG5CMGNWUjRNRFpJVDJKU2N6WndXVzAK
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
       ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4T1Mwd016STZORFp1Y2xkbk5UTT0iCgkJfQoJfQp9CgoK
type: kubernetes.io/dockerconfigjson
